apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k5sfuncjz-go-gitops
  description: This is GitOps manifest for k5sfuncjz-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=k5sfuncjz-go
    backstage.io/kubernetes-id: k5sfuncjz-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: k5sfuncjz-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:k5sfuncjz-go
