apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k5sfuncjz-go
  janus-idp.io/tekton: k5sfuncjz-go
  backstage.io/kubernetes-id: k5sfuncjz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k5sfuncjz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
